os: linux
sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - language: generic
      os: osx
      install: pip2 install tox-travis
      script: tox --skip-missing-interpreters
  allow_failures:
    - os: osx
install: pip install tox-travis
script: tox
